# filled by: kubectl -n kitchen create secret generic mq --from-literal=AMQP_URL=amqp://guest:guest@172.28.144.1:5672/ --dry-run=client -o yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: mq
  namespace: kitchen
type: Opaque
stringData:
  AMQP_URL: amqp://guest:guest@172.28.144.1:5672/
